In [11]:
f=pd.read_csv('complete dataset.csv')
EDA=f.describe()
EDA

,Total Population,Land Area: Kilometers Square,Population Density (People per sq. km),GDP per Capita,Percentage of Ethnic Minorities,Median Age,IMD Deprivation Score,4G Data Traffic (TB),Data Traffic (TB)
count,2.090000e+02,209.000000,209.000000,209.000000,209.000000,209.000000,209.000000,209.000000,209.000000
mean,1.743205e+05,355.201770,1880.344498,28979.071770,11.309569,42.280861,15256.404402,1367.435407,1505.153110
std,1.272367e+05,364.825254,2804.404180,13737.319808,13.822101,5.159943,5188.166776,1201.563711,1373.366392
min,5.139400e+04,15.540000,37.000000,14906.000000,1.100000,28.900000,3284.070000,256.000000,288.000000
25%,1.002650e+05,77.700000,229.000000,21098.000000,2.700000,38.700000,11000.880000,683.000000,736.000000
50%,1.310840e+05,212.380000,728.000000,25828.000000,5.200000,42.400000,15037.740000,952.000000,1026.000000
75%,2.088710e+05,564.620000,2349.000000,31317.000000,12.700000,46.200000,19550.800000,1542.000000,1677.000000
max,1.140525e+06,1758.610000,16427.000000,116624.000000,71.100000,54.300000,26417.750000,9962.000000,11434.000000

In [13]:
EDA.to_csv('moreEDA.csv')